"""empty message

Revision ID: 28de7bd9fb08
Revises: 18812bc6c2cb
Create Date: 2025-01-17 19:56:11.341986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28de7bd9fb08'
down_revision = '18812bc6c2cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cuenta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_tarjeta', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('cvv', sa.String(length=3), nullable=True))
        batch_op.create_unique_constraint(None, ['numero_tarjeta'])
        batch_op.create_unique_constraint(None, ['cvv'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cuenta', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('cvv')
        batch_op.drop_column('numero_tarjeta')

    # ### end Alembic commands ###
