"""empty message

Revision ID: 570bf4297ae7
Revises: 28de7bd9fb08
Create Date: 2025-01-20 16:27:31.982864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '570bf4297ae7'
down_revision = '28de7bd9fb08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cuenta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saldo_retenido', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cuenta', schema=None) as batch_op:
        batch_op.drop_column('saldo_retenido')

    # ### end Alembic commands ###
