"""empty message

Revision ID: a9fa1a65ac32
Revises: 
Create Date: 2025-01-26 18:04:58.108785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9fa1a65ac32'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=50), nullable=True),
    sa.Column('apellidos', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('tipo_documento', sa.String(length=50), nullable=True),
    sa.Column('numero_documento', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_documento')
    )
    op.create_table('configuracion_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('modo_oscuro', sa.Boolean(), nullable=True),
    sa.Column('idioma', sa.String(length=5), nullable=True),
    sa.Column('componentesSave', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cuenta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_cuenta', sa.String(length=20), nullable=True),
    sa.Column('numero_tarjeta', sa.String(length=20), nullable=True),
    sa.Column('cvv', sa.String(length=3), nullable=True),
    sa.Column('caducidad', sa.String(length=40), nullable=True),
    sa.Column('tipo_cuenta', sa.String(length=50), nullable=True),
    sa.Column('saldo', sa.Float(), nullable=True),
    sa.Column('saldo_retenido', sa.Float(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cvv'),
    sa.UniqueConstraint('numero_cuenta'),
    sa.UniqueConstraint('numero_tarjeta')
    )
    op.create_table('notificacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mensaje', sa.String(length=255), nullable=False),
    sa.Column('leida', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('reset_code', sa.String(length=6), nullable=True),
    sa.Column('code_expires', sa.DateTime(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('tarjeta_coordenadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=False),
    sa.Column('posicion', sa.String(length=2), nullable=False),
    sa.Column('valor', sa.String(length=4), nullable=False),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuenta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('depósito', 'retiro', 'transferencia', name='tipo_transaccion'), nullable=False),
    sa.Column('monto', sa.Float(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuenta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaccion')
    op.drop_table('tarjeta_coordenadas')
    op.drop_table('user')
    op.drop_table('notificacion')
    op.drop_table('cuenta')
    op.drop_table('configuracion_usuario')
    op.drop_table('cliente')
    # ### end Alembic commands ###
