"""empty message

Revision ID: aabeeedb713f
Revises: dcc6bd07f4c1
Create Date: 2025-01-14 13:58:05.780025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aabeeedb713f'
down_revision = 'dcc6bd07f4c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_code', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('code_expires', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('code_expires')
        batch_op.drop_column('reset_code')

    # ### end Alembic commands ###
